### ISSUE TITLE
com.example.blex.BlexApplication does not exist når jeg prøver å legge til variabler i config

### ISSUE THREAD

**Issue by Zohla** [sifterstudios/blex#25]
https://github.com/sifterstudios/blex/blob/39bb8a428b57123469f2b9bd93f62493e7436fa8/api/src/test/java/com/example/blex/BlexApplicationTests.java#L1

**Comment by sifterstudios** [comment]
Rart! "It works on my machine".. Er du på siste commit på main? Jeg renamet master til main i går
